### ISSUE TITLE
Code is not working with calling gpaw

### ISSUE THREAD

**Issue by beyzalisesivdin** [lrgresearch/gpaw-tools#14]
After 7918019758b0504a8571fcf8b46aa6118656251f or somewhere near, code is not working anymore with calling gpaw as:

    gpaw -P5 python gpawsolve.py -o -c config.py -i inputfile.cif

but working with:

    python gpawsolve.py -o -c config.py -i inputfile.cif

**Comment by sblisesivdin** [comment]
Ok. We can not parse more than one argument under gpaw command. I do not know why. However, with the 6e38e0ebac4284e2c0eeecbf832ef25d0c28883f commit, we can use the code with MPI with the commands:

For AMD CPUs or using Intel CPUs without hyperthreading: (Example CPU is intel here, 4 cores or 8 threads)
        $ mpirun -n 4 python gpawsolve.py <args>
 For using all threads provided by Intel Hyperthreading technology:
        $ mpirun --use-hwthread-cpus -n 8 python gpawsolve.py <args>

We need to change readme and usage page in website accordingly @beyzalisesivdin .
