### ISSUE TITLE
Unnecessary variables in config files

### ISSUE THREAD

**Issue by beyzalisesivdin** [lrgresearch/gpaw-tools#20]
Since v21.10.0, config files are used as input-parameters file, there are some parameters that do not related with computation: `WantCIFexport` and `draw_graphs`. Is it possible to move them as arguments to the `gpawsolve.py` command?

**Comment by sblisesivdin** [comment]
Yes, you are right. Firstly, there is no need for `WantCIFexport` variable. It can export every time after ground-state calculations. And for `draw_graphs`, yes it can be a new argument, therefore `gg.py` can call it everytime with that argument.

I think, it is a simple task.
