### ISSUE TITLE
Variable naming is not very elegant

### ISSUE THREAD

**Issue by sblisesivdin** [lrgresearch/gpaw-tools#37]
Some of the variables used CamelCase, some used Snake_case, some used lower_snake. So we must choose a case style. But this change will be a big thing. `gg.py` and `gpawsolve.py` must be edited at the same time. Also, it will make compatibility issues with the older versions. Examples must be changed also. However, before having a user base, we can do it asap.

**Comment by beyzalisesivdin** [comment]
Today, I added more comments to `gg.py`, to understand all objects better. Next, we must change generic labels and frames in gg.py. Then we must start to change variables.

**Comment by sblisesivdin** [comment]
With time, `gpawsolve.py` uses many variables in it and in input files. However, it does not have a proper naming convention for these variables. Also some of the variable names are misleading the user. From this version, `gpawsolve.py` will use a special Snake_case (first letter of each variable is capitalized) variables for the input file variables usage. Variables that are affected: *mode -> Mode, fmaxval -> Max_F_tolerance, whichstrain -> Relax_cell, cut_off_energy -> Cut_off_energy, kpts_density -> Ground_kpts_dens, kpts_x -> Ground_kpts_x, kpts_y -> Ground_kpts_y, kpts_z -> Ground_kpts_y, gpts_density -> Ground_gpts_dens, gpts_x -> Ground_gpts_x, gpts_y -> Ground_gpts_y, gpts_z -> Ground_gpts_z, Hubbard -> Setup_params, band_path -> Band_path, band_npoints -> Band_npoints, gridref -> Refine_grid energy_max -> Energy_max, GWtype -> GW_type, GWkpoints -> GW_kpoints_list, GWtruncation -> GW_truncation, GWcut_off_energy -> GW_cut_off_energy, GWbandVB -> GW_valence_band_no, GWbandCB -> GW_conduction_band_no, GWppa -> GW_PPA, GWq0correction -> GW_q0_correction, GWnblock -> GW_nblocks_max, GWbandinterpolation -> GW_interpolate_band, opttype -> Opt_calc_type, optshift -> Opt_shift_en, optBSEvb -> Opt_BSE_valence, optBSEcb -> Opt_BSE_conduction, optBSEminEn -> Opt_BSE_min_en, optBSEmaxEn -> Opt_BSE_max_en, optBSEnumdata -> Opt_BSE_num_of_data, num_of_bands -> Opt_num_of_bands, optFDsmear -> Opt_FD_smearing, opteta -> Opt_eta, optdomega0 -> Opt_domega0, optomega2 -> Opt_omega2, optecut -> Opt_cut_of_energy, optnblocks -> Opt_nblocks, MPIcores -> MPI_cores*

All new variable changes are corrected and new variables are added to `gg.py`.

The variables used in `asapsolve.py` is also changed. From this version, `asapsolve.py` will use a special Snake_case (first letter of each variable is capitalized) variables for the input file variables usage.Variable that are affected are: *Manualpbc -> Manual_PBC, pbcmanual -> PBC_constraints, PotentialUsed -> OpenKIM_potential, SolveDoubleElementProblem -> Solve_double_element_problem.*

New variable names have been started to be used with version 23.2.0
