### ISSUE TITLE
Spin calculation do not work with gpaw version 22.1.0

### ISSUE THREAD

**Issue by tugcehan** [lrgresearch/gpaw-tools#49]
I'm triying to perform the spin dependent calculation of WSe2. I use gpaw-tools 21.12.0 and the recent one 22.3.0. nothing changed. The program ended prematurely. However, when I'm using gpaw 21.6.0 instead of 22.1.0 it's working. Therefore, I think there is something wrong about the communication between the gpaw-tools and gpaw after gpaw version 22.1.0. 
Thanks in advance.

**Comment by sblisesivdin** [comment]
I can not reproduce the problem until now. 

If it continues, please open a new issue using the "**Bug report**" template. With a bug report template, you will be able to explain more about the problem, which will help the developers reproduce the problem.
